---
- name: Manage cron environment variables
  cron:
    name: '{{ item.name }}'
    disabled: '{{ item.disabled | d (omit) }}'
    env: yes
    insertbefore: '{{ item.insertbefore | d (omit) }}'
    insertafter: '{{ item.insertbefore | d (omit) }}'
    value: '{{ item.value }}'
    state: '{{ item.state | d ("present") }}'
  loop: '{{ n2cw_cron_envs }}'